CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_admin TINYINT(1) DEFAULT 0,
  is_approved TINYINT(1) DEFAULT 0,
  is_banned TINYINT(1) DEFAULT 0,
  reject_reason TEXT DEFAULT NULL
);